name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Symlink test data
        run: |
          ln -s $(pwd)/tests/test_data.xes $(pwd)/data/test_data.xes
      - name: Run pipelines
        run: |
          python pipelines/extract_xes.py
          python pipelines/transform_events.py
          python pipelines/read_metrics.py
          python pipelines/discover_strategies.py
      - name: Run tests
        run: pytest -q
